### PR TITLE
Fixed broken link

### PR DESCRIPTION
**Pull request by PanMan**
Link was broken.

### CODE REVIEW

**Comment by sdepold** [comment]
Thanks :)

**Comment by sdepold** [comment]
OK I'm officially confused. The original source is here: https://github.com/sdepold/node-imageable-server

**Comment by PanMan** [comment]
The link to https://github.com/dawanda/node-imageable 404's
https://github.com/dawanda/node-imageable
https://github.com/sdepold/node-imageable works. So that's what I changed

**Comment by sdepold** [comment]
yeah but dawanda/node-imageable-server is not the right target for your PR as this is just the fork of https://github.com/sdepold/node-imageable-server

edit: I assume at least that you wanted to submit the PR to the original source's repository. If that is note the case, please ignore me.

**Comment by PanMan** [comment]
The link on the frontpage points to dawanda. And is broken. This isn't about node-imageable-server but the node-imageable project. Right?

**Comment by sdepold** [comment]
Aaaaah :D I see. Just fixed the link

**Comment by PanMan** [comment]
:+1:

**Pull request merged**
